- hosts: elasticmaster
  roles:
    - role: elastic.elasticsearch
  vars:
    es_heap_size: "1g"
    es_config:
      node.name: "elasticmaster"
      cluster.name: "test-cluster"
      cluster.initial_master_nodes: "elasticmaster"
      discovery.seed_hosts: "elasticmaster:9300"
      http.host: 0.0.0.0
      http.port: 9200
      node.data: false
      node.master: true
      transport.host: 0.0.0.0
      transport.port: 9300
      bootstrap.memory_lock: false
    es_plugins:
     - plugin: ingest-attachment

- hosts: elasticnode1
  roles:
    - role: elastic.elasticsearch
  vars:
    es_data_dirs:
      - "/opt/elasticsearch"
    es_config:
      node.name: "elasticnode1"
      cluster.name: "test-cluster"
      cluster.initial_master_nodes: "elasticmaster"
      discovery.seed_hosts: "elasticmaster:9300"
      http.host: 0.0.0.0
      http.port: 9200
      node.data: true
      node.master: false
      transport.host: 0.0.0.0
      transport.port: 9300
      bootstrap.memory_lock: false
    es_plugins:
      - plugin: ingest-attachment

- hosts: elasticnode2
  roles:
    - role: elastic.elasticsearch
  vars:
    es_config:
      node.name: "elasticnode2"
      cluster.name: "test-cluster"
      discovery.seed_hosts: "elasticmaster:9300"
      http.host: 0.0.0.0
      http.port: 9200
      node.data: true
      node.master: false
      transport.host: 0.0.0.0
      transport.port: 9300
      bootstrap.memory_lock: false
    es_plugins:
      - plugin: ingest-attachment
