- hosts: elasticmaster
  roles:
    - role: elastic.elasticsearch
  vars:
    es_heap_size: "1g"
    es_config:
      cluster.name: "terra-ansible"
      cluster.initial_master_nodes: "elasticmaster"
      discovery.seed_hosts: "elasticmaster:9300"
      http.host: 0.0.0.0
      http.port: 9200
      node.data: true
      node.master: true
      transport.host: 0.0.0.0
      transport.port: 9300
      bootstrap.memory_lock: false
    es_plugins:
     - plugin: ingest-attachment
    es_api_basic_auth_username: elastic
    es_api_basic_auth_password: "{{ ansible_ssh_pass }}"
    es_xpack_trial: true

- hosts: elasticnode1
  roles:
    - role: elastic.elasticsearch
  vars:
    es_data_dirs:
      - "/opt/elasticsearch"
    es_config:
      cluster.name: "terra-ansible"
      cluster.initial_master_nodes: "elasticmaster"
      discovery.seed_hosts: "elasticmaster:9300"
      http.host: 0.0.0.0
      http.port: 9200
      node.data: true
      node.master: false
      transport.host: 0.0.0.0
      transport.port: 9300
      bootstrap.memory_lock: false
    es_plugins:
      - plugin: ingest-attachment
    es_api_basic_auth_username: elastic
    es_api_basic_auth_password: "{{ ansible_ssh_pass }}"
    es_xpack_trial: true

- hosts: elasticnode2
  roles:
    - role: elastic.elasticsearch
  vars:
    es_config:
      cluster.name: "terra-ansible"
      discovery.seed_hosts: "elasticmaster:9300"
      http.host: 0.0.0.0
      http.port: 9200
      node.data: true
      node.master: false
      transport.host: 0.0.0.0
      transport.port: 9300
      bootstrap.memory_lock: false
    es_plugins:
      - plugin: ingest-attachment
    es_api_basic_auth_username: elastic
    es_api_basic_auth_password: "{{ ansible_ssh_pass }}"
    es_xpack_trial: true

- hosts: elastic
  roles:
    - role: elastic.beats
  vars:
    beats_version: 7.13.4
    beat: metricbeat
    beat_conf:
      metricbeat.config.modules:
          path: '${path.config}/modules.d/*.yml'
          reload.enabled: false
      setup.template.settings:
        index.number_of_shards: 1
        index.codec: best_compression
      processors:
        - add_host_metadata: ~
    output_conf:
      elasticsearch:
        hosts: ['localhost:9200']
        username: "elastic"
        password: "{{ ansible_ssh_pass }}"

- hosts: elastic
  roles:
    - role: elastic.beats
  vars:
    beats_version: 7.13.4
    beat: filebeat
    beat_conf:
      filebeat:
        inputs:
          - type: log
            enabled: true
            paths:
              - /var/log/*.log
    output_conf:
      elasticsearch:
        hosts: ['localhost:9200']
        username: "elastic"
        password: "{{ ansible_ssh_pass }}"